#!/usr/bin/env python
# -*- coding: utf-8 -*-
# 读取excel数据
import xlrd
import jieba
import jieba.analyse
def excelRead(filename):
	data = xlrd.open_workbook('Majoranalyse.xlsx') # 打开xls文件
	table = data.sheets()[0] # 打开第一张表
	nrows = table.nrows      # 获取表的行数
	for i in range(nrows):   # 循环逐行打印
		with open(filename,'a',encoding='utf-8') as f:
			f.write(table.row_values(i)[0])
		f.close()
def majorAnalyse(filename):
	with open(filename,'r',encoding='utf-8') as f:
		sentence=f.read()
		keywords = jieba.analyse.extract_tags(sentence, topK=40, withWeight=True, allowPOS=('n','nr','ns'))
		for item in keywords:
			print(item[0],item[1])
def main(filename): 
	excelRead(filename)
	majorAnalyse(filename)
if __name__ == '__main__':
	main('majorfinalanalysis.txt')
	
